export type EstimatorMode="time"|"price";
export type EstimatorCondition="maintained"|"attention"|"heavy"|"very_heavy";
export type EstimatorPhase="base"|"detail";
export type EstimatorCategory="bedroom"|"bathroom"|"kitchen"|"common"|"basement";
export type EstimatorBasis="bedrooms"|"bathrooms"|"property"|"basement"|"item";
export type MinuteRange={min:number;max:number};
export type EstimatorTask={id:string;category:EstimatorCategory;phase:EstimatorPhase;label:string;description?:string;pricingType:"labour_minutes";min:number;max:number;basis:EstimatorBasis;baseline:boolean;helper?:string;wall:boolean;defaultQty?:number;customerVisible:boolean;priceModeVisible:boolean;requiresDisclaimer:boolean;adminActive:boolean;sortOrder:number;serviceTypes:string[];conditionProfile?:"detail"|"window"};
export type EstimatorRecommendation={id:string;trigger:"kitchen"|"bedroom_carpet"|"pets"|"move_out"|"bathroom"|"basement";title:string;description:string;taskIds:string[];enablesCarpet:boolean;customerVisible:boolean;adminActive:boolean;sortOrder:number};
export type EstimatorConfig={version:string;baseCents:number;includedMinutes:number;extraHourCents:number;incrementMinutes:number;gstEnabled:boolean;gstRate:number;carpetMinimumCents:number;carpetRoomCents:number;carpetLargeRoomCents:number;carpetHallCents:number;carpetStairsCents:number;carpetStairStepCap?:number;carpetClosetCents:number;carpetHeavyFromCents:number;carpetSetupMinutes:MinuteRange;carpetRoomMinutes:MinuteRange;carpetLargeRoomMinutes:MinuteRange;carpetHallMinutes:MinuteRange;carpetStairsMinutes:MinuteRange;carpetClosetMinutes:MinuteRange;carpetHeavyMinutes:MinuteRange;conditionFactors:Record<EstimatorCondition,number>;detailConditionMinutes:Record<EstimatorCondition,MinuteRange>;windowConditionMinutes:Record<EstimatorCondition,MinuteRange>;manualQuoteMinutes:number;wallManualQuoteQuantity:number;popupTriggerMinutes:number;timeModeEnabled:boolean;priceModeEnabled:boolean;wallDisclaimer:string;carpetDisclaimer:string;nearIncludedMessage:string;exceededIncludedMessage:string;fixedTimeDisclaimer:string;consentTerms:string[]};

export const DEFAULT_ESTIMATOR_CONFIG:EstimatorConfig={
  version:"camz-estimator-2026-09-v2",baseCents:17900,includedMinutes:240,extraHourCents:4000,incrementMinutes:15,gstEnabled:true,gstRate:.05,
  carpetMinimumCents:10000,carpetRoomCents:4000,carpetLargeRoomCents:6000,carpetHallCents:2500,carpetStairsCents:5000,carpetStairStepCap:14,carpetClosetCents:1500,carpetHeavyFromCents:2500,
  carpetSetupMinutes:{min:30,max:45},carpetRoomMinutes:{min:20,max:30},carpetLargeRoomMinutes:{min:30,max:45},carpetHallMinutes:{min:10,max:15},carpetStairsMinutes:{min:20,max:30},carpetClosetMinutes:{min:5,max:10},carpetHeavyMinutes:{min:10,max:30},
  conditionFactors:{maintained:1,attention:1.2,heavy:1.45,very_heavy:1.75},detailConditionMinutes:{maintained:{min:10,max:10},attention:{min:15,max:20},heavy:{min:25,max:35},very_heavy:{min:40,max:60}},windowConditionMinutes:{maintained:{min:7,max:10},attention:{min:12,max:15},heavy:{min:20,max:25},very_heavy:{min:30,max:40}},
  manualQuoteMinutes:600,wallManualQuoteQuantity:3,popupTriggerMinutes:210,timeModeEnabled:true,priceModeEnabled:true,
  wallDisclaimer:"Stain and mark removal is not guaranteed. Permanent stains, ink, grease, discoloration, paint transfer, damage, marks absorbed into paint, and delicate or damaged paint finishes may remain or may limit the cleaning method that can safely be used.",
  carpetDisclaimer:"Professional carpet cleaning improves soil removal and appearance, but stain, odour and discoloration removal is not guaranteed. Results depend on carpet fibre, age, prior treatments, contamination, stain type and depth. Specialty stain or pet treatment may require assessment and additional charges.",
  nearIncludedMessage:"Your customized cleaning is estimated to use most of the included 4 man-hours. You can keep adding the areas that matter to you. If additional cleaning time is likely, we’ll include it in your estimate below.",
  exceededIncludedMessage:"Your selected cleaning is estimated to need some additional time beyond the included 4 man-hours. We’ve updated the estimated cleaning time below. You can continue customizing or choose your priority areas.",
  fixedTimeDisclaimer:"This is a time-based service. The team will work through your selected priorities during the booked time. Completion of every selected item is not guaranteed within a fixed time allowance.",
  consentTerms:["Estimated time is based on the information and selections provided during booking.","Actual cleaning time may be less or more depending on condition, buildup, clutter, accessibility, materials and the amount of work required.","For fixed-time bookings, selected priority areas are addressed first and completion of every selected task is not guaranteed within the booked time.","Spot, stain, wall-mark, carpet-stain and odour removal cannot be guaranteed.","Additional services or extra time are charged only according to the booking authorization and Camz policy shown at checkout.","Customer should identify delicate, damaged, specialty or restricted surfaces before work begins."],
};

let order=0;
const t=(id:string,category:EstimatorCategory,phase:EstimatorPhase,label:string,min:number,max:number,basis:EstimatorBasis,extra:Partial<EstimatorTask>={}):EstimatorTask=>({id,category,phase,label,min,max,basis,pricingType:"labour_minutes",baseline:false,wall:false,customerVisible:true,priceModeVisible:true,requiresDisclaimer:false,adminActive:true,sortOrder:order+=10,serviceTypes:["professional_cleaning"],...extra});
export const DEFAULT_ESTIMATOR_TASKS:EstimatorTask[]=[
  t("bed_dust","bedroom","base","General dusting and accessible surfaces",8,12,"bedrooms",{baseline:true}),t("bed_vacuum","bedroom","base","Vacuum flooring",5,10,"bedrooms",{baseline:true}),t("bed_mop","bedroom","base","Mop hard flooring",5,8,"bedrooms"),t("bed_furniture","bedroom","base","Wipe accessible furniture surfaces",5,10,"bedrooms",{baseline:true}),
  t("bed_baseboards","bedroom","detail","Detail baseboards",8,12,"bedrooms"),t("bed_sills","bedroom","detail","Clean window sills and ledges",3,5,"item",{defaultQty:1}),t("bed_windows","bedroom","detail","Clean interior window glass",7,10,"item",{defaultQty:1,conditionProfile:"window"}),t("bed_blinds","bedroom","detail","Detail blinds",10,10,"item",{defaultQty:1,conditionProfile:"detail"}),t("bed_doors","bedroom","detail","Wipe doors and frames",3,6,"bedrooms"),t("bed_closet","bedroom","detail","Clean accessible empty closet interior",10,20,"item",{defaultQty:1,helper:"Closet must be empty and accessible."}),t("bed_wall_spot","bedroom","detail","Spot-clean accessible wall marks",15,30,"item",{defaultQty:1,wall:true,requiresDisclaimer:true}),t("bed_wall_full","bedroom","detail","Full wall washing",30,60,"item",{defaultQty:1,wall:true,requiresDisclaimer:true,helper:"Large or heavily soiled walls may require assessment."}),
  t("bath_toilet","bathroom","base","Clean and disinfect toilet",7,10,"bathrooms",{baseline:true}),t("bath_sink","bathroom","base","Clean sink, vanity and counter",7,10,"bathrooms",{baseline:true}),t("bath_mirror","bathroom","base","Clean mirror",3,5,"bathrooms",{baseline:true}),t("bath_tub","bathroom","base","Routine tub or shower cleaning",10,15,"bathrooms",{baseline:true}),t("bath_floor","bathroom","base","Vacuum and mop bathroom floor",5,8,"bathrooms",{baseline:true}),
  t("bath_cabinets","bathroom","detail","Wipe exterior cabinets",5,8,"bathrooms"),t("bath_baseboards","bathroom","detail","Detail baseboards",5,8,"bathrooms"),t("bath_doors","bathroom","detail","Wipe doors and frames",3,5,"bathrooms"),t("bath_soap","bathroom","detail","Heavy soap scum or mineral buildup",15,30,"item",{defaultQty:1,helper:"Apply only to affected bathrooms."}),t("bath_grout","bathroom","detail","Detailed grout attention",15,30,"item",{defaultQty:1}),t("bath_wall_spot","bathroom","detail","Spot-clean accessible wall marks",10,20,"item",{defaultQty:1,wall:true,requiresDisclaimer:true}),t("bath_wall_full","bathroom","detail","Full bathroom wall washing",25,45,"item",{defaultQty:1,wall:true,requiresDisclaimer:true}),
  t("kit_surfaces","kitchen","base","Counters and accessible surfaces",8,12,"property",{baseline:true}),t("kit_sink","kitchen","base","Clean sink and faucet",5,8,"property",{baseline:true}),t("kit_cooktop","kitchen","base","Clean cooktop exterior",8,12,"property",{baseline:true}),t("kit_appliances","kitchen","base","Wipe appliance exteriors",8,12,"property",{baseline:true}),t("kit_floor","kitchen","base","Vacuum and mop kitchen floor",10,15,"property",{baseline:true}),
  t("kit_backsplash","kitchen","detail","Detail backsplash",5,10,"property"),t("kit_cabinet_fronts","kitchen","detail","Detail cabinet fronts",10,20,"property"),t("kit_baseboards","kitchen","detail","Detail baseboards",8,12,"property"),t("kit_oven","kitchen","detail","Clean inside oven",30,60,"item",{defaultQty:1,helper:"Severe carbon buildup may require assessment."}),t("kit_fridge","kitchen","detail","Clean inside emptied refrigerator",25,45,"item",{defaultQty:1,helper:"Customer removes food before arrival."}),t("kit_cabinets","kitchen","detail","Clean inside emptied cabinets",45,90,"property",{helper:"Cabinets must be empty and accessible."}),t("kit_grease","kitchen","detail","Heavy grease or buildup",30,120,"property",{helper:"Results depend on material and severity."}),t("kit_wall_spot","kitchen","detail","Spot-clean accessible wall marks",15,30,"property",{wall:true,requiresDisclaimer:true}),t("kit_wall_full","kitchen","detail","Full kitchen wall washing",30,60,"property",{wall:true,requiresDisclaimer:true}),
  t("common_living","common","base","Living room general cleaning",25,40,"property",{baseline:true}),t("common_dining","common","base","Dining area cleaning",15,25,"property",{baseline:true}),t("common_hall","common","base","Hall and entrance cleaning",10,20,"property",{baseline:true}),t("common_stairs","common","base","Vacuum and wipe standard staircase",10,20,"item",{defaultQty:1}),
  t("common_baseboards","common","detail","Detail common-area baseboards",15,30,"property"),t("common_sills","common","detail","Clean window sills",3,5,"item",{defaultQty:4}),t("common_windows","common","detail","Clean interior window glass",7,10,"item",{defaultQty:4,conditionProfile:"window"}),t("common_blinds","common","detail","Detail blinds",10,10,"item",{defaultQty:4,conditionProfile:"detail"}),t("common_doors","common","detail","Detail interior doors and frames",3,6,"item",{defaultQty:3}),t("common_wall_spot","common","detail","Spot-clean wall marks in selected area",15,30,"item",{defaultQty:1,wall:true,requiresDisclaimer:true}),t("common_wall_full","common","detail","Full wall washing in selected area",30,60,"item",{defaultQty:1,wall:true,requiresDisclaimer:true}),t("common_pet_hair","common","detail","Heavy pet-hair detailing",30,90,"property"),
  t("basement_general","basement","base","Basement common-area cleaning",30,60,"basement",{baseline:true}),t("basement_stairs","basement","detail","Detail basement stairs",10,20,"basement"),t("basement_baseboards","basement","detail","Detail basement baseboards",15,30,"basement"),
];

export const DEFAULT_ESTIMATOR_RECOMMENDATIONS:EstimatorRecommendation[]=[
  {id:"kitchen_detail",trigger:"kitchen",title:"Add appliance and kitchen detailing",description:"Complete the kitchen with oven, fridge, cabinets, backsplash and wall-mark options.",taskIds:["kit_oven","kit_fridge","kit_cabinets","kit_backsplash","kit_wall_spot"],enablesCarpet:false,customerVisible:true,adminActive:true,sortOrder:10},
  {id:"bedroom_carpet",trigger:"bedroom_carpet",title:"Complete the bedroom detailing",description:"Add a deeper carpet clean plus baseboards, blinds and accessible wall marks.",taskIds:["bed_baseboards","bed_blinds","bed_wall_spot"],enablesCarpet:true,customerVisible:true,adminActive:true,sortOrder:20},
  {id:"pets",trigger:"pets",title:"Add pet-focused detailing",description:"Add pet-hair labour and, where needed, a carpet stain or odour assessment.",taskIds:["common_pet_hair"],enablesCarpet:true,customerVisible:true,adminActive:true,sortOrder:30},
  {id:"move_out",trigger:"move_out",title:"Add move-out essentials",description:"Add cabinet and appliance interiors, walls, carpet steam and interior windows.",taskIds:["kit_cabinets","kit_oven","kit_fridge","kit_wall_full","common_windows"],enablesCarpet:true,customerVisible:true,adminActive:true,sortOrder:40},
  {id:"bathroom_detail",trigger:"bathroom",title:"Complete the bathroom detailing",description:"Add grout, buildup, baseboards and accessible wall-mark attention.",taskIds:["bath_grout","bath_soap","bath_baseboards","bath_wall_spot"],enablesCarpet:false,customerVisible:true,adminActive:true,sortOrder:50},
  {id:"basement_detail",trigger:"basement",title:"Add a deeper basement clean",description:"Add carpet steam where applicable, detailed stairs and common-area finishing.",taskIds:["basement_stairs","basement_baseboards","common_baseboards"],enablesCarpet:true,customerVisible:true,adminActive:true,sortOrder:60},
];

type SupabaseLike={from:(table:string)=>any};
const n=(value:unknown,fallback:number)=>Number.isFinite(Number(value))?Number(value):fallback;
const range=(row:any,prefix:string,fallback:MinuteRange):MinuteRange=>({min:n(row?.[`${prefix}_min`],fallback.min),max:n(row?.[`${prefix}_max`],fallback.max)});
export async function loadEstimatorDefinition(client:SupabaseLike){
  const [settingsResult,tasksResult,recommendationsResult]=await Promise.all([client.from("cleaning_estimator_settings").select("*").eq("id",true).maybeSingle(),client.from("cleaning_estimator_tasks").select("*").eq("admin_active",true).eq("customer_visible",true).order("sort_order"),client.from("cleaning_estimator_recommendations").select("*").eq("admin_active",true).eq("customer_visible",true).order("sort_order")]);
  const row=settingsResult.data,f=DEFAULT_ESTIMATOR_CONFIG;
  const config:EstimatorConfig=row?{version:row.version||f.version,baseCents:n(row.base_price_cents,f.baseCents),includedMinutes:n(row.included_minutes,f.includedMinutes),extraHourCents:n(row.extra_hour_cents,f.extraHourCents),incrementMinutes:n(row.billing_increment_minutes,f.incrementMinutes),gstEnabled:row.gst_enabled!==false,gstRate:n(row.gst_rate,f.gstRate),carpetMinimumCents:n(row.carpet_minimum_cents,f.carpetMinimumCents),carpetRoomCents:n(row.carpet_room_cents,f.carpetRoomCents),carpetLargeRoomCents:n(row.carpet_large_room_cents,f.carpetLargeRoomCents),carpetHallCents:n(row.carpet_hall_cents,f.carpetHallCents),carpetStairsCents:n(row.carpet_stairs_cents,f.carpetStairsCents),carpetClosetCents:n(row.carpet_closet_cents,f.carpetClosetCents),carpetHeavyFromCents:n(row.carpet_heavy_from_cents,f.carpetHeavyFromCents),carpetSetupMinutes:range(row,"carpet_setup_minutes",f.carpetSetupMinutes),carpetRoomMinutes:range(row,"carpet_room_minutes",f.carpetRoomMinutes),carpetLargeRoomMinutes:range(row,"carpet_large_room_minutes",f.carpetLargeRoomMinutes),carpetHallMinutes:range(row,"carpet_hall_minutes",f.carpetHallMinutes),carpetStairsMinutes:range(row,"carpet_stairs_minutes",f.carpetStairsMinutes),carpetClosetMinutes:range(row,"carpet_closet_minutes",f.carpetClosetMinutes),carpetHeavyMinutes:range(row,"carpet_heavy_minutes",f.carpetHeavyMinutes),conditionFactors:{maintained:n(row.condition_maintained_factor,1),attention:n(row.condition_attention_factor,1.2),heavy:n(row.condition_heavy_factor,1.45),very_heavy:n(row.condition_very_heavy_factor,1.75)},detailConditionMinutes:{maintained:range(row,"detail_maintained",f.detailConditionMinutes.maintained),attention:range(row,"detail_attention",f.detailConditionMinutes.attention),heavy:range(row,"detail_heavy",f.detailConditionMinutes.heavy),very_heavy:range(row,"detail_very_heavy",f.detailConditionMinutes.very_heavy)},windowConditionMinutes:{maintained:range(row,"window_maintained",f.windowConditionMinutes.maintained),attention:range(row,"window_attention",f.windowConditionMinutes.attention),heavy:range(row,"window_heavy",f.windowConditionMinutes.heavy),very_heavy:range(row,"window_very_heavy",f.windowConditionMinutes.very_heavy)},manualQuoteMinutes:n(row.manual_quote_minutes,f.manualQuoteMinutes),wallManualQuoteQuantity:n(row.wall_manual_quote_quantity,f.wallManualQuoteQuantity),popupTriggerMinutes:n(row.popup_trigger_minutes,f.popupTriggerMinutes),timeModeEnabled:row.time_mode_enabled!==false,priceModeEnabled:row.price_mode_enabled!==false,wallDisclaimer:row.wall_disclaimer||f.wallDisclaimer,carpetDisclaimer:row.carpet_disclaimer||f.carpetDisclaimer,nearIncludedMessage:row.near_included_message||f.nearIncludedMessage,exceededIncludedMessage:row.exceeded_included_message||f.exceededIncludedMessage,fixedTimeDisclaimer:row.fixed_time_disclaimer||f.fixedTimeDisclaimer,consentTerms:Array.isArray(row.consent_terms)&&row.consent_terms.length?row.consent_terms:f.consentTerms}:f;
  const tasks:EstimatorTask[]=tasksResult.data?.length?tasksResult.data.map((item:any)=>({id:item.task_id,category:item.category,phase:item.phase,label:item.label,description:item.description||undefined,pricingType:item.pricing_type||"labour_minutes",min:item.minutes_min,max:item.minutes_max,basis:item.quantity_basis,baseline:item.included_in_base_template??item.baseline??false,helper:item.helper||undefined,wall:item.requires_disclaimer===true||item.wall_disclaimer===true,defaultQty:item.default_quantity||undefined,customerVisible:item.customer_visible!==false,priceModeVisible:item.price_mode_visible!==false,requiresDisclaimer:item.requires_disclaimer===true,adminActive:item.admin_active!==false,sortOrder:item.sort_order||0,serviceTypes:Array.isArray(item.service_types)?item.service_types:["professional_cleaning"],conditionProfile:item.condition_profile||undefined})):DEFAULT_ESTIMATOR_TASKS;
  const recommendations:EstimatorRecommendation[]=recommendationsResult.data?.length?recommendationsResult.data.map((item:any)=>({id:item.rule_id,trigger:item.trigger_type,title:item.title,description:item.description,taskIds:item.task_ids||[],enablesCarpet:item.enables_carpet===true,customerVisible:item.customer_visible!==false,adminActive:item.admin_active!==false,sortOrder:item.sort_order||0})):DEFAULT_ESTIMATOR_RECOMMENDATIONS;
  return {config:{...config,carpetStairStepCap:row?n(row.carpet_stair_step_cap,config.carpetStairStepCap||14):config.carpetStairStepCap},tasks,recommendations};
}

export function calculateAuthoritativeEstimate(input:{mode:EstimatorMode;budget:"fixed"|"extend";property:{bedrooms:number;fullBaths:number;halfBaths:number;size:string;basement:string;condition:EstimatorCondition;cleaners:number;clutter?:string;excessiveClutter?:boolean;delicateWalls?:boolean;unusualScope?:boolean};carpet:{enabled:boolean;rooms:number;largeRooms:number;halls:number;stairs:number;closets:number;heavySoil:boolean;petTreatment:boolean};selected:Array<{task_id:string;quantity?:number;condition?:EstimatorCondition}>},config:EstimatorConfig,tasks:EstimatorTask[]){
  const sizes:Record<string,number>={"under-900":.9,"900-1499":1,"1500-1999":1.15,"2000-2499":1.3,"2500-plus":1.5},selectedMap=new Map(input.selected.map(item=>[item.task_id,item]));
  const qty=(task:EstimatorTask)=>{const explicit=Number(selectedMap.get(task.id)?.quantity);if(Number.isFinite(explicit)&&explicit>0){const safe=Math.max(.5,Math.min(30,explicit));return task.basis==="property"?safe*(sizes[input.property.size]||1):safe;}if(task.basis==="bedrooms")return input.property.bedrooms;if(task.basis==="bathrooms")return input.property.fullBaths+input.property.halfBaths*.6;if(task.basis==="basement")return input.property.basement==="none"?0:1;if(task.basis==="item")return task.defaultQty||1;return sizes[input.property.size]||1;};
  const taskRange=(task:EstimatorTask)=>{const condition=selectedMap.get(task.id)?.condition||input.property.condition;if(task.conditionProfile==="window")return config.windowConditionMinutes[condition];if(task.conditionProfile==="detail")return config.detailConditionMinutes[condition];const factor=config.conditionFactors[input.property.condition]||1;return {min:task.min*factor,max:task.max*factor};};
  const selectedTasks=tasks.filter(task=>selectedMap.has(task.id)&&task.adminActive&&task.customerVisible).map(task=>{const r=taskRange(task);return {task_id:task.id,category:task.category,label:task.label,minutes_min:r.min,minutes_max:r.max,quantity:qty(task),quantity_basis:task.basis,condition:selectedMap.get(task.id)?.condition||input.property.condition};});
  const minutes=selectedTasks.reduce((sum,task)=>({min:sum.min+task.minutes_min*task.quantity,max:sum.max+task.minutes_max*task.quantity}),{min:0,max:0}),shown={...minutes};
  const priceFor=(value:number)=>{if(input.budget==="fixed"||value<=config.includedMinutes)return config.baseCents;const extra=Math.ceil((value-config.includedMinutes)/config.incrementMinutes)*config.incrementMinutes;return config.baseCents+Math.round(extra/60*config.extraHourCents);},general={min:priceFor(minutes.min),max:priceFor(minutes.max)},c=input.carpet;
  const carpetSelected=c.enabled&&c.rooms+c.largeRooms+c.halls+c.stairs+c.closets>0,carpetComponents=(c.rooms>0?config.carpetMinimumCents+Math.max(0,c.rooms-1)*config.carpetRoomCents:0)+c.largeRooms*config.carpetLargeRoomCents+c.halls*config.carpetHallCents+c.stairs*config.carpetStairsCents+c.closets*config.carpetClosetCents+(c.heavySoil?config.carpetHeavyFromCents:0),carpetPrice=carpetSelected?Math.max(config.carpetMinimumCents,carpetComponents):0;
  const carpetMinutes=carpetSelected?{min:config.carpetSetupMinutes.min+Math.max(0,c.rooms-1)*config.carpetRoomMinutes.min+c.largeRooms*config.carpetLargeRoomMinutes.min+c.halls*config.carpetHallMinutes.min+c.stairs*config.carpetStairsMinutes.min+c.closets*config.carpetClosetMinutes.min+(c.heavySoil?config.carpetHeavyMinutes.min:0),max:config.carpetSetupMinutes.max+Math.max(0,c.rooms-1)*config.carpetRoomMinutes.max+c.largeRooms*config.carpetLargeRoomMinutes.max+c.halls*config.carpetHallMinutes.max+c.stairs*config.carpetStairsMinutes.max+c.closets*config.carpetClosetMinutes.max+(c.heavySoil?config.carpetHeavyMinutes.max:0)}:{min:0,max:0};
  const subtotal={min:general.min+carpetPrice,max:general.max+carpetPrice},gst={min:config.gstEnabled?Math.round(subtotal.min*config.gstRate):0,max:config.gstEnabled?Math.round(subtotal.max*config.gstRate):0},total={min:subtotal.min+gst.min,max:subtotal.max+gst.max};
  const wallQty=selectedTasks.filter(task=>task.task_id.includes("wall_full")).reduce((sum,task)=>sum+task.quantity,0),reasons:string[]=[];if(input.property.condition==="very_heavy")reasons.push("Very heavy or neglected condition");if((input.property.condition==="heavy"&&wallQty>0)||wallQty>=config.wallManualQuoteQuantity||(input.property.delicateWalls&&wallQty>0))reasons.push("Large, heavily soiled or delicate wall scope");if(c.petTreatment)reasons.push("Specialty carpet stain or odour treatment");if(input.property.unusualScope||minutes.max>config.manualQuoteMinutes)reasons.push("Very large or unusual scope");const cleaners=Math.max(1,Math.min(4,Number(input.property.cleaners)||1));
  return {selectedTasks,estimate:{estimator_version:config.version,mode:input.mode,general_minutes_min:Math.round(minutes.min),general_minutes_max:Math.round(minutes.max),display_minutes_min:Math.round(shown.min),display_minutes_max:Math.round(shown.max),general_man_hours_min:Number((minutes.min/60).toFixed(2)),general_man_hours_max:Number((minutes.max/60).toFixed(2)),cleaner_count:cleaners,onsite_minutes_min:Math.round(minutes.min/cleaners),onsite_minutes_max:Math.round(minutes.max/cleaners),carpet_service_minutes_min:Math.round(carpetMinutes.min),carpet_service_minutes_max:Math.round(carpetMinutes.max),base_price_cents:config.baseCents,included_minutes:config.includedMinutes,additional_hour_cents:config.extraHourCents,billing_increment_minutes:config.incrementMinutes,budget_choice:input.budget,general_price_min_cents:input.mode==="price"?general.min:null,general_price_max_cents:input.mode==="price"?general.max:null,carpet_price_cents:input.mode==="price"?carpetPrice:null,carpet_treatment_price_cents:c.petTreatment?null:0,subtotal_min_cents:input.mode==="price"?subtotal.min:null,subtotal_max_cents:input.mode==="price"?subtotal.max:null,gst_enabled:config.gstEnabled,gst_rate:config.gstRate,gst_min_cents:input.mode==="price"?gst.min:null,gst_max_cents:input.mode==="price"?gst.max:null,total_min_cents:input.mode==="price"?total.min:null,total_max_cents:input.mode==="price"?total.max:null,requires_manual_quote:reasons.length>0,manual_quote_reasons:reasons,calculated_at:new Date().toISOString()}};
}
