"use client";

import { FormEvent, ReactNode, useEffect, useState } from "react";
import { BarChart3, Save, Settings2 } from "lucide-react";

type Settings=Record<string,unknown>;
type Task={task_id:string;category:string;phase:string;label:string;description:string|null;pricing_type:string;minutes_min:number;minutes_max:number;quantity_basis:string;included_in_base_template:boolean;customer_visible:boolean;price_mode_visible:boolean;requires_disclaimer:boolean;admin_active:boolean;sort_order:number;service_types:string[];condition_profile:string|null};
type Rule={rule_id:string;trigger_type:string;title:string;description:string;task_ids:string[];enables_carpet:boolean;customer_visible:boolean;admin_active:boolean;sort_order:number};
type Performance={sample_size:number;average_error_percent:number;underestimated:number;overestimated:number;within_ten_percent:number;task_bias:Array<[string,{samples:number;error_percent:number}]>};

const moneyFields=[
  ["base_price_cents","Base package ($)"],["extra_hour_cents","Extra labour / hour ($)"],["carpet_minimum_cents","Carpet minimum ($)"],
  ["carpet_room_cents","Standard carpet room ($)"],["carpet_large_room_cents","Large carpet room ($)"],["carpet_hall_cents","Carpet hall ($)"],
  ["carpet_stairs_cents","Carpet staircase ($)"],["carpet_closet_cents","Walk-in closet ($)"],["carpet_heavy_from_cents","Heavy soil from ($)"],
] as const;
const generalMinutes=[
  ["included_minutes","Included man-minutes"],["billing_increment_minutes","Billing increment"],["manual_quote_minutes","Large-scope review threshold"],
  ["wall_manual_quote_quantity","Full-wall area threshold"],["carpet_stair_step_cap","Steps per standard carpet staircase"],["popup_trigger_minutes","Near-included-time trigger"],
] as const;
const carpetRanges=[
  ["carpet_setup_minutes","Equipment setup"],["carpet_room_minutes","Standard room"],["carpet_large_room_minutes","Large room"],
  ["carpet_hall_minutes","Hallway"],["carpet_stairs_minutes","Staircase"],["carpet_closet_minutes","Walk-in closet"],["carpet_heavy_minutes","Heavy-soil allowance"],
] as const;
const conditions=[
  ["maintained","Normal / maintained"],["attention","Needs extra attention"],["heavy","Heavy buildup"],["very_heavy","Very heavy / neglected"],
] as const;
const textFields=[
  ["wall_disclaimer","Wall disclaimer"],["carpet_disclaimer","Carpet disclaimer"],["near_included_message","Near 4-hour message"],
  ["exceeded_included_message","Past 4-hour message"],["fixed_time_disclaimer","Fixed-time disclaimer"],
] as const;

export default function EstimatorSettingsPage(){
  const [settings,setSettings]=useState<Settings|null>(null),[tasks,setTasks]=useState<Task[]>([]),[rules,setRules]=useState<Rule[]>([]),[analytics,setAnalytics]=useState<Record<string,number>>({}),[performance,setPerformance]=useState<Performance|null>(null);
  const [status,setStatus]=useState<"loading"|"idle"|"saving"|"saved"|"error">("loading"),[message,setMessage]=useState("");
  useEffect(()=>{fetch("/api/admin/estimator-settings").then(async response=>({ok:response.ok,data:await response.json()})).then(({ok,data})=>{if(!ok)throw new Error(data.error);setSettings(data.settings);setTasks(data.tasks||[]);setRules(data.recommendations||[]);setAnalytics(data.analytics||{});setPerformance(data.performance||null);setStatus("idle");}).catch(error=>{setMessage(error.message||"Could not load settings.");setStatus("error");});},[]);
  const setSetting=(key:string,value:unknown)=>setSettings(current=>current?{...current,[key]:value}:current);
  const setTask=(id:string,field:keyof Task,value:unknown)=>setTasks(current=>current.map(item=>item.task_id===id?{...item,[field]:value}:item));
  const setRule=(id:string,field:keyof Rule,value:unknown)=>setRules(current=>current.map(item=>item.rule_id===id?{...item,[field]:value}:item));
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!settings)return;setStatus("saving");setMessage("");const response=await fetch("/api/admin/estimator-settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({settings,tasks,recommendations:rules})});const result=await response.json().catch(()=>({}));if(!response.ok){setMessage(result.error||"Save failed.");setStatus("error");return;}setStatus("saved");setMessage("All estimator settings saved. New customer calculations use them immediately.");};
  if(status==="loading")return <div className="p-6 text-sm text-slate-500">Loading estimator settings…</div>;
  if(!settings)return <div className="m-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{message}</div>;
  const consentTerms=Array.isArray(settings.consent_terms)?(settings.consent_terms as string[]).join("\n"):"";
  return <form onSubmit={submit} className="mx-auto max-w-[1600px] space-y-5 p-4 sm:p-6">
    {performance&&<Section title="Estimate vs actual performance"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><MetricBox label="Completed samples" value={String(performance.sample_size)}/><MetricBox label="Average error" value={`${performance.average_error_percent}%`}/><MetricBox label="Underestimated" value={String(performance.underestimated)}/><MetricBox label="Overestimated" value={String(performance.overestimated)}/><MetricBox label="Within ±10%" value={String(performance.within_ten_percent)}/></div>{performance.task_bias.length>0&&<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[480px] text-left text-xs"><thead className="text-slate-500"><tr><th className="p-2">Task ID</th><th className="p-2">Samples</th><th className="p-2">Error</th><th className="p-2">Finding</th></tr></thead><tbody>{performance.task_bias.map(([taskId,value])=><tr key={taskId} className="border-t border-slate-100"><td className="p-2 font-mono">{taskId}</td><td className="p-2">{value.samples}</td><td className="p-2">{value.error_percent}%</td><td className="p-2">{value.error_percent>10?"Usually underestimated":value.error_percent< -10?"Usually overestimated":"Within target"}</td></tr>)}</tbody></table></div>}</Section>}
    <Section title="Task availability by service type"><p className="mb-4 text-xs text-slate-500">Use comma-separated service IDs. The customer estimator currently uses <code>professional_cleaning</code>.</p><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{tasks.map(item=><label key={item.task_id} className="text-[11px] font-semibold text-slate-600">{item.label}<input className="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3 font-mono text-[10px]" value={(item.service_types||[]).join(", ")} onChange={event=>setTask(item.task_id,"service_types",event.target.value.split(",").map(value=>value.trim()).filter(Boolean))}/></label>)}</div></Section>
    <header className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-blue-50 p-3 text-[#0B4E9B]"><Settings2 size={22}/></span><div><p className="text-[10px] font-extrabold uppercase tracking-wider text-[#4A86F7]">Cleaning estimator</p><h1 className="text-xl font-bold text-[#13263A]">Complete time, price and content controls</h1></div></div><p className="mt-3 text-sm text-slate-500">These settings drive both customer modes and the server-authoritative saved estimate.</p></header>

    <Section title="Pricing and modes"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{moneyFields.map(([key,label])=><NumberField key={key} label={label} value={Number(settings[key]||0)/100} step="0.01" onChange={value=>setSetting(key,Math.round(Number(value)*100))}/>)}{generalMinutes.map(([key,label])=><NumberField key={key} label={label} value={Number(settings[key]||0)} onChange={value=>setSetting(key,Math.round(Number(value)))}/>)}<NumberField label="GST (%)" value={Number(settings.gst_rate||0)*100} step="0.01" onChange={value=>setSetting("gst_rate",Number(value)/100)}/></div><div className="mt-5 flex flex-wrap gap-5 rounded-lg bg-slate-50 p-4"><Toggle label="Apply GST" checked={settings.gst_enabled!==false} onChange={value=>setSetting("gst_enabled",value)}/><Toggle label="Offer time-only mode" checked={settings.time_mode_enabled===true} onChange={value=>setSetting("time_mode_enabled",value)}/><Toggle label="Offer live-price mode" checked={settings.price_mode_enabled===true} onChange={value=>setSetting("price_mode_enabled",value)}/></div></Section>

    <Section title="Condition multipliers and supplied timing tables"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{conditions.map(([id,label])=><div key={id} className="rounded-lg border border-slate-200 p-4"><h3 className="text-xs font-bold text-slate-800">{label}</h3><NumberField label="General multiplier" value={Number(settings[`condition_${id}_factor`]||1)} step="0.01" onChange={value=>setSetting(`condition_${id}_factor`,Number(value))}/><div className="mt-3 grid grid-cols-2 gap-2"><NumberField label="Detail min" value={Number(settings[`detail_${id}_min`]||0)} onChange={value=>setSetting(`detail_${id}_min`,Number(value))}/><NumberField label="Detail max" value={Number(settings[`detail_${id}_max`]||0)} onChange={value=>setSetting(`detail_${id}_max`,Number(value))}/><NumberField label="Window min" value={Number(settings[`window_${id}_min`]||0)} onChange={value=>setSetting(`window_${id}_min`,Number(value))}/><NumberField label="Window max" value={Number(settings[`window_${id}_max`]||0)} onChange={value=>setSetting(`window_${id}_max`,Number(value))}/></div></div>)}</div></Section>

    <Section title="Carpet service-time rules"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{carpetRanges.map(([prefix,label])=><div key={prefix} className="rounded-lg border border-slate-200 p-4"><h3 className="text-xs font-bold">{label}</h3><div className="mt-2 grid grid-cols-2 gap-2"><NumberField label="Min" value={Number(settings[`${prefix}_min`]||0)} onChange={value=>setSetting(`${prefix}_min`,Number(value))}/><NumberField label="Max" value={Number(settings[`${prefix}_max`]||0)} onChange={value=>setSetting(`${prefix}_max`,Number(value))}/></div></div>)}</div></Section>

    <Section title="Disclaimers, notices and consent"><div className="grid gap-4 lg:grid-cols-2">{textFields.map(([key,label])=><TextField key={key} label={label} value={String(settings[key]||"")} onChange={value=>setSetting(key,value)}/>)}<TextField label="Consent terms (one per line)" value={consentTerms} onChange={value=>setSetting("consent_terms",value.split("\n").map(line=>line.trim()).filter(Boolean))}/></div></Section>

    <Section title="Contextual recommendation rules"><div className="grid gap-4 xl:grid-cols-2">{rules.map(rule=><div key={rule.rule_id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-extrabold uppercase text-[#4A86F7]">{rule.trigger_type.replaceAll("_"," ")}</p><NumberField label="Order" value={rule.sort_order} onChange={value=>setRule(rule.rule_id,"sort_order",Number(value))}/></div><input className="mt-3 h-10 w-full rounded-lg border border-slate-200 px-3 text-sm font-semibold" value={rule.title} onChange={event=>setRule(rule.rule_id,"title",event.target.value)}/><textarea className="mt-2 w-full rounded-lg border border-slate-200 p-3 text-sm" value={rule.description} onChange={event=>setRule(rule.rule_id,"description",event.target.value)}/><label className="mt-2 block text-xs font-semibold">Task IDs, comma separated<input className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-3 font-mono text-xs" value={rule.task_ids.join(", ")} onChange={event=>setRule(rule.rule_id,"task_ids",event.target.value.split(",").map(value=>value.trim()).filter(Boolean))}/></label><div className="mt-3 flex flex-wrap gap-4"><Toggle label="Enable carpet" checked={rule.enables_carpet} onChange={value=>setRule(rule.rule_id,"enables_carpet",value)}/><Toggle label="Customer visible" checked={rule.customer_visible} onChange={value=>setRule(rule.rule_id,"customer_visible",value)}/><Toggle label="Active" checked={rule.admin_active} onChange={value=>setRule(rule.rule_id,"admin_active",value)}/></div></div>)}</div></Section>

    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="font-bold text-[#13263A]">Checklist task database</h2><p className="mt-1 text-xs text-slate-500">Labels, descriptions, time, availability, mode visibility and order are editable.</p></div><div className="overflow-x-auto"><table className="min-w-[1350px] w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-3">Area</th><th className="p-3">Task / description</th><th className="p-3">Min</th><th className="p-3">Max</th><th className="p-3">Basis</th><th className="p-3">Condition profile</th><th className="p-3">Order</th><th className="p-3">Base</th><th className="p-3">Visible</th><th className="p-3">Price mode</th><th className="p-3">Disclaimer</th><th className="p-3">Active</th></tr></thead><tbody className="divide-y divide-slate-100">{tasks.map(item=><tr key={item.task_id}><td className="p-3 capitalize text-slate-500">{item.category}<br/><span className="text-[10px]">{item.phase}</span></td><td className="p-3"><input className="h-9 w-full rounded-lg border border-slate-200 px-3" value={item.label} onChange={event=>setTask(item.task_id,"label",event.target.value)}/><input placeholder="Optional description" className="mt-1 h-8 w-full rounded-lg border border-slate-200 px-3 text-[11px]" value={item.description||""} onChange={event=>setTask(item.task_id,"description",event.target.value)}/></td><td className="p-3"><SmallNumber value={item.minutes_min} onChange={value=>setTask(item.task_id,"minutes_min",value)}/></td><td className="p-3"><SmallNumber value={item.minutes_max} min={item.minutes_min} onChange={value=>setTask(item.task_id,"minutes_max",value)}/></td><td className="p-3"><select className="h-9 rounded border border-slate-200" value={item.quantity_basis} onChange={event=>setTask(item.task_id,"quantity_basis",event.target.value)}>{["bedrooms","bathrooms","property","basement","item"].map(value=><option key={value}>{value}</option>)}</select></td><td className="p-3"><select className="h-9 rounded border border-slate-200" value={item.condition_profile||""} onChange={event=>setTask(item.task_id,"condition_profile",event.target.value||null)}><option value="">General</option><option value="detail">Detail</option><option value="window">Window</option></select></td><td className="p-3"><SmallNumber value={item.sort_order} onChange={value=>setTask(item.task_id,"sort_order",value)}/></td>{(["included_in_base_template","customer_visible","price_mode_visible","requires_disclaimer","admin_active"] as const).map(field=><td key={field} className="p-3"><input type="checkbox" className="h-4 w-4 accent-[#0B4E9B]" checked={item[field]} onChange={event=>setTask(item.task_id,field,event.target.checked)}/></td>)}</tr>)}</tbody></table></div></section>

    <Section title="Recent estimator analytics"><div className="flex items-center gap-3 text-[#0B4E9B]"><BarChart3 size={20}/><p className="text-xs text-slate-500">Mode, funnel, recommendation and budget events from the latest 1,000 records.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(analytics).map(([key,value])=><div key={key} className="rounded-lg bg-slate-50 p-3"><p className="text-[10px] uppercase text-slate-500">{key.replaceAll("_"," ")}</p><p className="mt-1 text-xl font-bold text-[#0B4E9B]">{value}</p></div>)}</div></Section>

    <div className="sticky bottom-4 flex items-center gap-3 rounded-xl border border-slate-200 bg-white/95 p-4 shadow-lg backdrop-blur"><p className={`text-xs ${status==="error"?"text-red-600":"text-emerald-700"}`}>{message}</p><button disabled={status==="saving"} className="ml-auto inline-flex h-10 items-center gap-2 rounded-lg bg-[#0B4E9B] px-5 text-sm font-bold text-white disabled:opacity-50"><Save size={16}/>{status==="saving"?"Saving…":"Save all settings"}</button></div>
  </form>;
}

function MetricBox({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-3"><p className="text-[10px] uppercase text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-[#0B4E9B]">{value}</p></div>}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 font-bold text-[#13263A]">{title}</h2>{children}</section>}
function NumberField({label,value,step="1",onChange}:{label:string;value:number;step?:string;onChange:(value:string)=>void}){return <label className="block text-[11px] font-semibold text-slate-600">{label}<input type="number" min="0" step={step} value={value} onChange={event=>onChange(event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-slate-200 px-3 text-sm text-slate-900"/></label>}
function SmallNumber({value,min=0,onChange}:{value:number;min?:number;onChange:(value:number)=>void}){return <input type="number" min={min} value={value} onChange={event=>onChange(Number(event.target.value))} className="h-9 w-20 rounded-lg border border-slate-200 px-2"/>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="flex items-center gap-2 text-xs font-semibold text-slate-700"><input type="checkbox" className="h-4 w-4 accent-[#0B4E9B]" checked={checked} onChange={event=>onChange(event.target.checked)}/>{label}</label>}
function TextField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="text-xs font-semibold text-slate-600">{label}<textarea rows={5} value={value} onChange={event=>onChange(event.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-200 p-3 text-sm text-slate-900"/></label>}
